Officially support Python 3.12
nextstrain/cli pull request #368
Opened 2024-04-30 22:32 UTC by corneliusroemer

## Description of proposed changes

- Officially support Python 3.12
- Remove setup.py code irrelevant since 3.6/3.7 were dropped in https://github.com/nextstrain/cli/pull/327

## Related issue(s)

- Mirrors #327 

## Checklist

- [ ] Checks pass
- [ ] Changelog edited

2024-04-30 23:46 UTC, genehack approved these changes

2024-05-01 05:50 UTC, tsibley requested changes

2024-05-01 05:50 UTC, tsibley commented on CHANGES.md
> +([#TBD](https://github.com/nextstrain/cli/pull/TBD))
need to fill this TBD in :-)

2024-05-01 05:50 UTC, tsibley commented on CHANGES.md
> +([c.f.](https://docs.nextstrain.org/projects/cli/en/8.3.0/installation/)).  It
This link shouldn't be version-specific here. It should at least be version-agnostic

```suggestion
([c.f.](https://docs.nextstrain.org/projects/cli/page/installation/)).  It
```

or, better yet, reflect the version it's released as



```suggestion
([c.f.](https://docs.nextstrain.org/projects/cli/en/__NEXT__/installation/)).  It
```

(See c05b0447587fdd45375badee924e162ebdb65fd2 for how that works.)

2024-05-01 05:50 UTC, tsibley commented on setup.py
> +            "types-requests",
\o/ Thanks for spotting this!

2024-05-09 17:53 UTC, tsibley commented
Closing in favor of #369.

2024-05-09 17:53 UTC, closed without merging